# Experiment #03
#### For this experiment, I will make the features that are ranked fully random, and also to make the number of appearing university to be different aswell

In [245]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn import preprocessing

from copy import deepcopy

In [246]:
df = pd.read_csv('./cwurData_V3.csv')

In [247]:
df.drop(columns={'score'}, inplace=True)
df.head()


quality_of_education  alumni_employment  quality_of_faculty  publications  \
0                     7                  9                   1             1   
1                     9                 17                   3            12   
2                    17                 11                   5             4   
3                    10                 24                   4            16   
4                     2                 29                   7            37   

   influence  citations  patents  institution  
0          1          1        5            0  
1          4          4        1            1  
2          2          2       15            2  
3         16         11       50            3  
4         22         22       18            4

In [248]:
df.shape

(4816, 8)

#### Dropping Duplicates

In [249]:
df.drop_duplicates(keep='first', inplace=True)
df.shape

(601, 8)

In [250]:
df['institution'].value_counts()

0      4
68     4
66     4
65     4
64     4
      ..
135    2
134    2
133    2
201    2
94     1
Name: institution, Length: 202, dtype: int64

#### Producing Random features for each institute

In [251]:
df1 = deepcopy(df)

df1['quality_of_education'] = np.random.randint(df1['quality_of_education'].min(), df1['quality_of_education'].max(), df1.shape[0])
df1['alumni_employment'] = np.random.randint(df1['alumni_employment'].min(), df1['alumni_employment'].max(), df1.shape[0])
df1['quality_of_faculty'] = np.random.randint(df1['quality_of_faculty'].min(), df1['quality_of_faculty'].max(), df1.shape[0])
df1['publications'] = np.random.randint(df1['publications'].min(), df1['publications'].max(), df1.shape[0])
df1['influence'] = np.random.randint(df1['influence'].min(), df1['influence'].max(), df1.shape[0])
df1['citations'] = np.random.randint(df1['citations'].min(), df1['citations'].max(), df1.shape[0])
df1['patents'] = np.random.randint(df1['patents'].min(), df1['patents'].max(), df1.shape[0])

df1.head()
print(df1.shape)

(601, 8)


In [252]:
print(df1.shape)
df1['institution'].value_counts()


(601, 8)


0      4
68     4
66     4
65     4
64     4
      ..
135    2
134    2
133    2
201    2
94     1
Name: institution, Length: 202, dtype: int64

In [253]:
df2 = deepcopy(df)

df2['quality_of_education'] = np.random.randint(
    df2['quality_of_education'].min(), df2['quality_of_education'].max(), df2.shape[0])
df2['alumni_employment'] = np.random.randint(
    df2['alumni_employment'].min(), df2['alumni_employment'].max(), df2.shape[0])
df2['quality_of_faculty'] = np.random.randint(
    df2['quality_of_faculty'].min(), df2['quality_of_faculty'].max(), df2.shape[0])
df2['publications'] = np.random.randint(
    df2['publications'].min(), df2['publications'].max(), df2.shape[0])
df2['influence'] = np.random.randint(
    df2['influence'].min(), df2['influence'].max(), df2.shape[0])
df2['citations'] = np.random.randint(
    df2['citations'].min(), df2['citations'].max(), df2.shape[0])
df2['patents'] = np.random.randint(
    df2['patents'].min(), df2['patents'].max(), df2.shape[0])

df2.head()
print(df2.shape)


(601, 8)


In [254]:
df3 = deepcopy(df)

df3['quality_of_education'] = np.random.randint(
    df3['quality_of_education'].min(), df3['quality_of_education'].max(), df3.shape[0])
df3['alumni_employment'] = np.random.randint(
    df3['alumni_employment'].min(), df3['alumni_employment'].max(), df3.shape[0])
df3['quality_of_faculty'] = np.random.randint(
    df3['quality_of_faculty'].min(), df3['quality_of_faculty'].max(), df3.shape[0])
df3['publications'] = np.random.randint(
    df3['publications'].min(), df3['publications'].max(), df3.shape[0])
df3['influence'] = np.random.randint(
    df3['influence'].min(), df3['influence'].max(), df3.shape[0])
df3['citations'] = np.random.randint(
    df3['citations'].min(), df3['citations'].max(), df3.shape[0])
df3['patents'] = np.random.randint(
    df3['patents'].min(), df3['patents'].max(), df3.shape[0])

df3.head()
print(df3.shape)

(601, 8)


In [255]:
df4 = deepcopy(df)

df4['quality_of_education'] = np.random.randint(
    df4['quality_of_education'].min(), df4['quality_of_education'].max(), df4.shape[0])
df4['alumni_employment'] = np.random.randint(
    df4['alumni_employment'].min(), df4['alumni_employment'].max(), df4.shape[0])
df4['quality_of_faculty'] = np.random.randint(
    df4['quality_of_faculty'].min(), df4['quality_of_faculty'].max(), df4.shape[0])
df4['publications'] = np.random.randint(
    df4['publications'].min(), df4['publications'].max(), df4.shape[0])
df4['influence'] = np.random.randint(
    df4['influence'].min(), df4['influence'].max(), df4.shape[0])
df4['citations'] = np.random.randint(
    df4['citations'].min(), df4['citations'].max(), df4.shape[0])
df4['patents'] = np.random.randint(
    df4['patents'].min(), df4['patents'].max(), df4.shape[0])

df4.head()
print(df4.shape)


(601, 8)


In [256]:
df5 = deepcopy(df)

df5['quality_of_education'] = np.random.randint(
    df5['quality_of_education'].min(), df5['quality_of_education'].max(), df5.shape[0])
df5['alumni_employment'] = np.random.randint(
    df5['alumni_employment'].min(), df5['alumni_employment'].max(), df5.shape[0])
df5['quality_of_faculty'] = np.random.randint(
    df5['quality_of_faculty'].min(), df5['quality_of_faculty'].max(), df5.shape[0])
df5['publications'] = np.random.randint(
    df5['publications'].min(), df5['publications'].max(), df5.shape[0])
df5['influence'] = np.random.randint(
    df5['influence'].min(), df5['influence'].max(), df5.shape[0])
df5['citations'] = np.random.randint(
    df5['citations'].min(), df5['citations'].max(), df5.shape[0])
df5['patents'] = np.random.randint(
    df5['patents'].min(), df5['patents'].max(), df5.shape[0])

df5.head()
print(df5.shape)


(601, 8)


In [257]:
df6 = deepcopy(df)

df6['quality_of_education'] = np.random.randint(
    df6['quality_of_education'].min(), df6['quality_of_education'].max(), df6.shape[0])
df6['alumni_employment'] = np.random.randint(
    df6['alumni_employment'].min(), df6['alumni_employment'].max(), df6.shape[0])
df6['quality_of_faculty'] = np.random.randint(
    df6['quality_of_faculty'].min(), df6['quality_of_faculty'].max(), df6.shape[0])
df6['publications'] = np.random.randint(
    df6['publications'].min(), df6['publications'].max(), df6.shape[0])
df6['influence'] = np.random.randint(
    df6['influence'].min(), df6['influence'].max(), df6.shape[0])
df6['citations'] = np.random.randint(
    df6['citations'].min(), df6['citations'].max(), df6.shape[0])
df6['patents'] = np.random.randint(
    df6['patents'].min(), df6['patents'].max(), df6.shape[0])

df6.head()
print(df6.shape)


(601, 8)


In [258]:
df7 = deepcopy(df)

df7['quality_of_education'] = np.random.randint(
    df7['quality_of_education'].min(), df7['quality_of_education'].max(), df7.shape[0])
df7['alumni_employment'] = np.random.randint(
    df7['alumni_employment'].min(), df7['alumni_employment'].max(), df7.shape[0])
df7['quality_of_faculty'] = np.random.randint(
    df7['quality_of_faculty'].min(), df7['quality_of_faculty'].max(), df7.shape[0])
df7['publications'] = np.random.randint(
    df7['publications'].min(), df7['publications'].max(), df7.shape[0])
df7['influence'] = np.random.randint(
    df7['influence'].min(), df7['influence'].max(), df7.shape[0])
df7['citations'] = np.random.randint(
    df7['citations'].min(), df7['citations'].max(), df7.shape[0])
df7['patents'] = np.random.randint(
    df7['patents'].min(), df7['patents'].max(), df7.shape[0])

df7.head()
print(df7.shape)


(601, 8)


In [259]:
df8 = deepcopy(df)

df8['quality_of_education'] = np.random.randint(
    df8['quality_of_education'].min(), df8['quality_of_education'].max(), df8.shape[0])
df8['alumni_employment'] = np.random.randint(
    df8['alumni_employment'].min(), df8['alumni_employment'].max(), df8.shape[0])
df8['quality_of_faculty'] = np.random.randint(
    df8['quality_of_faculty'].min(), df8['quality_of_faculty'].max(), df8.shape[0])
df8['publications'] = np.random.randint(
    df8['publications'].min(), df8['publications'].max(), df8.shape[0])
df8['influence'] = np.random.randint(
    df8['influence'].min(), df8['influence'].max(), df8.shape[0])
df8['citations'] = np.random.randint(
    df8['citations'].min(), df8['citations'].max(), df8.shape[0])
df8['patents'] = np.random.randint(
    df8['patents'].min(), df8['patents'].max(), df8.shape[0])

df8.head()
print(df8.shape)


(601, 8)


In [260]:
df9 = deepcopy(df)

df9['quality_of_education'] = np.random.randint(
    df9['quality_of_education'].min(), df9['quality_of_education'].max(), df9.shape[0])
df9['alumni_employment'] = np.random.randint(
    df9['alumni_employment'].min(), df9['alumni_employment'].max(), df9.shape[0])
df9['quality_of_faculty'] = np.random.randint(
    df9['quality_of_faculty'].min(), df9['quality_of_faculty'].max(), df9.shape[0])
df9['publications'] = np.random.randint(
    df9['publications'].min(), df9['publications'].max(), df9.shape[0])
df9['influence'] = np.random.randint(
    df9['influence'].min(), df9['influence'].max(), df9.shape[0])
df9['citations'] = np.random.randint(
    df9['citations'].min(), df9['citations'].max(), df9.shape[0])
df9['patents'] = np.random.randint(
    df9['patents'].min(), df9['patents'].max(), df9.shape[0])

df9.head()
print(df9.shape)
print(df9['institution'].value_counts)


(601, 8)
<bound method IndexOpsMixin.value_counts of 0        0
1        1
2        2
3        3
4        4
      ... 
597    191
598    168
599    190
600    155
601    152
Name: institution, Length: 601, dtype: int64>


In [261]:
df10 = deepcopy(df)

df10['quality_of_education'] = np.random.randint(
    df10['quality_of_education'].min(), df10['quality_of_education'].max(), df10.shape[0])
df10['alumni_employment'] = np.random.randint(
    df10['alumni_employment'].min(), df10['alumni_employment'].max(), df10.shape[0])
df10['quality_of_faculty'] = np.random.randint(
    df10['quality_of_faculty'].min(), df10['quality_of_faculty'].max(), df10.shape[0])
df10['publications'] = np.random.randint(
    df10['publications'].min(), df10['publications'].max(), df10.shape[0])
df10['influence'] = np.random.randint(
    df10['influence'].min(), df10['influence'].max(), df10.shape[0])
df10['citations'] = np.random.randint(
    df10['citations'].min(), df10['citations'].max(), df10.shape[0])
df10['patents'] = np.random.randint(
    df10['patents'].min(), df10['patents'].max(), df10.shape[0])

df10.head()
print(df10.shape)
print(df10['institution'].value_counts)

(601, 8)
<bound method IndexOpsMixin.value_counts of 0        0
1        1
2        2
3        3
4        4
      ... 
597    191
598    168
599    190
600    155
601    152
Name: institution, Length: 601, dtype: int64>


In [279]:
new_data = pd.concat([df, df1, df2, df3, df4, df5, df6, df7,
                     df8, df9, df10], axis=0)
new_data.shape
new_data.head()

quality_of_education  alumni_employment  quality_of_faculty  publications  \
0                     7                  9                   1             1   
1                     9                 17                   3            12   
2                    17                 11                   5             4   
3                    10                 24                   4            16   
4                     2                 29                   7            37   

   influence  citations  patents  institution  
0          1          1        5            0  
1          4          4        1            1  
2          2          2       15            2  
3         16         11       50            3  
4         22         22       18            4

In [271]:
print(new_data['institution'].value_counts)


<bound method IndexOpsMixin.value_counts of 0        0
1        1
2        2
3        3
4        4
      ... 
597    191
598    168
599    190
600    155
601    152
Name: institution, Length: 6611, dtype: int64>


# Applying KNN

In [273]:

X = new_data.iloc[:, 0:7]
y = new_data.iloc[:, 7]

MinMaxScaler = preprocessing.MinMaxScaler()
X_data_minmax = MinMaxScaler.fit_transform(X)
# data = pd.DataFrame(X_data_minmax, columns=['quality_of_education', 'alumni_employment', 'quality_of_faculty', 'publications', 'influence', 'citations',  'patents', 'score'])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=0, test_size=0.3)


In [274]:
X

quality_of_education  alumni_employment  quality_of_faculty  \
0                       7                  9                   1   
1                       9                 17                   3   
2                      17                 11                   5   
3                      10                 24                   4   
4                       2                 29                   7   
..                    ...                ...                 ...   
597                    10                 96                  76   
598                    41                 94                 109   
599                    46                438                  51   
600                    12                423                  97   
601                   121                455                  56   

     publications  influence  citations  patents  
0               1          1          1        5  
1              12          4          4        1  
2               4          2          2       15  
3              16         16         11       50  
4              37         22         22       18  
..            ...        ...        ...      ...  
597           347        523        124      704  
598           717        194        390      805  
599            62        181        642       55  
600           930        146        289      307  
601           860        832        569       42  

[6611 rows x 7 columns]

In [275]:
y

0        0
1        1
2        2
3        3
4        4
      ... 
597    191
598    168
599    190
600    155
601    152
Name: institution, Length: 6611, dtype: int64

In [276]:
knn_clf=KNeighborsClassifier()
knn_clf.fit(X_train,y_train)
ypred=knn_clf.predict(X_test) #These are the predicted output values

In [277]:
print(len(X_train))
print(len(y_train))
print(len(X_test))
print(len(y_test))


4627
4627
1984
1984


In [278]:

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, ypred)
print("Confusion Matrix: ")
print(result)
result1 = classification_report(y_test, ypred)
print("Classification Report: " ,)
print (result1)
result2 = accuracy_score(y_test,ypred)
print("Accuracy: ",result2)

Confusion Matrix: 
[[5 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 3 ... 1 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [1 0 0 ... 0 0 2]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.10      0.42      0.17        12
           1       0.10      0.30      0.15        10
           2       0.07      0.21      0.11        14
           3       0.03      0.10      0.04        10
           4       0.04      0.08      0.05        12
           5       0.03      0.14      0.04         7
           6       0.05      0.18      0.08        11
           7       0.04      0.11      0.06         9
           8       0.08      0.18      0.11        17
           9       0.05      0.25      0.08         8
          10       0.06      0.17      0.09        12
          11       0.10      0.29      0.14        14
          12       0.07      0.23      0.10        13
          13       0.06      0.14      0.08        14
          14       0.32   

/home/nafay/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/nafay/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/nafay/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
